architecture: "resNet1"
resnet: True
input_width: 108
input_height: 1
num_classes: 7
n_components: 108
lr: 0.00034871215254438895
weight_decay: 0.09553107856344323

num_blocks: 3
blocks_per_group: 1
resBlock_step: .7
res_drop: .25

